Repository bosagora/stoa, pull requests merged in 2020-10, with the labels that each got.

#147 Add `await` in front of `assert.rejects`
  tests/Storage.test.ts
Labels: type-bug

#146 Simplify construction of `Height`
  src/Stoa.ts
  src/modules/storage/LedgerStorage.ts
  tests/Recovery.test.ts
  tests/Storage.test.ts
  tests/Utils.test.ts
Labels: type-refactoring

#158 Remove TaskManager and rely on Promises instead
  src/Stoa.ts
  src/modules/task/TaskManager.ts
  tests/Recovery.test.ts
  tests/Stoa.test.ts
Labels: type-refactoring

#162 Dockerfile: Depends on Node 14.x
  Dockerfile
Labels: prio-URGENT, type-bug
